name: lightshot_parser_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  photo_view: ^0.14.0
  path_provider: ^2.1.2
  http: ^1.2.1
  permission_handler: ^11.3.0
  share_plus: ^8.0.2
  dio: ^5.4.2+1
  flutter_local_notifications: ^17.0.1

  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"
  package_rename: ^1.5.3

flutter:
  uses-material-design: true
  assets:
  - assets/icons/logo.png
  - assets/icons/logo_with_background.png
flutter_intl:
  enabled: true
  localizely:
    project_id: 61630f63-677a-49fe-beda-3beb45abe85c

#dart run flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icons/logo_with_background.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  windows:
    generate: true
    image_path: "assets/icons/logo_with_background.png"
    icon_size: 48 # min:48, max:256, default: 48

#dart run package_rename
package_rename_config:
  android:
    app_name: Lightshot Parser
    package_name: com.valvekat.lightshotParserMobile

  ios:
    app_name: Lightshot Parser
    bundle_name: lightshotparser
    package_name: com.valvekat.lightshotParserMobile

  web:
    app_name: Lightshot Parser
    description: Program for parsing photos from prnt.sc

  linux:
    app_name: Lightshot Parser
    package_name: com.valvekat.lightshotParserMobile
    exe_name: lightshot_parser_mobile

  windows:
    app_name: Lightshot Parser
    organization: MaksimLevchenko
    copyright_notice: Copyright ©️ 2024 MaksimLevchenko. All rights reserved.
    exe_name: lightshot_parser_mobile

  macos:
    app_name: Lightshot Parser
    package_name: MaksimLevchenko
    copyright_notice: Copyright ©️ 2024 MaksimLevchenko. All rights reserved. 
  